import Foundation

enum ArtifactKind {
    static let renderPDF = "render-pdf"
    static let screenshotPNG = "screenshot-png"
    static let fileSnapshot = "file-snapshot"
}

/// The identity captured at the moment Render opens.  Keeping this alongside
/// the PDF means the library survives panel removal, host outages, and session
/// renames instead of depending on whatever happens to be live later.
struct ArtifactPanelContext: Codable, Hashable {
    let machineID: String
    let machineName: String
    let machineHost: String
    let sessionName: String
    let stableSessionID: String?
    /// Identifies one backend session lifetime. Unlike tmux's reusable `$N`
    /// transport handle, this includes the tmux server generation and is safe
    /// to use only as an alias bridge (rename/cwd changes) in the archive.
    let sessionLineageID: String?
    let folder: String

    init(
        machineID: String,
        machineName: String,
        machineHost: String,
        sessionName: String,
        stableSessionID: String?,
        sessionLineageID: String? = nil,
        folder: String
    ) {
        self.machineID = machineID
        self.machineName = machineName
        self.machineHost = machineHost
        self.sessionName = sessionName
        self.stableSessionID = stableSessionID
        self.sessionLineageID = sessionLineageID
        self.folder = folder
    }

    /// The durable, logical identity of a panel. A panel can `cd` freely and be
    /// recreated after a restart, so cwd is metadata rather than identity. The
    /// user-controlled panel name is the stable namespace within a machine
    /// scope. tmux `$N` is deliberately absent because tmux reuses it.
    var key: String { semanticKey }

    var semanticKey: String {
        Self.identityKey(prefix: "panel-v2", parts: [
            machineScope,
            sessionName.trimmingCharacters(in: .whitespacesAndNewlines),
        ])
    }

    /// A rename or cwd change alters the semantic key. Records captured during
    /// the same live session carry this second key, allowing the query layer to
    /// union those semantic aliases without trusting a reusable tmux handle.
    var lineageKey: String? {
        guard let lineage = sessionLineageID?.trimmingCharacters(in: .whitespacesAndNewlines),
              !lineage.isEmpty else { return nil }
        // A lineage is generated by one broker/tmux server, so keep its
        // physical host in the namespace even when semantic panel identity is
        // shared across Babel. Two Babel workers can legitimately produce the
        // same PID/creation-time/$N tuple; that must never alias two names.
        return Self.identityKey(prefix: "lineage-v1", parts: [physicalMachineScope, lineage])
    }

    var machineScope: String {
        let candidates = [machineName, machineHost, machineID]
            .map(Self.normalizedMachineComponent)
            .filter { !$0.isEmpty }
        if candidates.contains(where: { value in
            var first = value.split(separator: ".", maxSplits: 1).first.map(String.init) ?? value
            if first.hasPrefix("ut-") { first.removeFirst(3) }
            return first.hasPrefix("babel-")
        }) {
            // Babel nodes expose one shared filesystem and routinely move a
            // logical panel between workers. Treat the cluster as one scope.
            return "shared:babel"
        }
        if machineID == "local" { return "local" }
        let host = Self.normalizedMachineComponent(machineHost)
        if !host.isEmpty { return "host:" + host }
        let id = Self.normalizedMachineComponent(machineID)
        if !id.isEmpty { return "machine:" + id }
        return "name:" + Self.normalizedMachineComponent(machineName)
    }

    private var physicalMachineScope: String {
        if machineID == "local" { return "local" }
        let host = Self.normalizedMachineComponent(machineHost)
        if !host.isEmpty { return "host:" + host }
        let id = Self.normalizedMachineComponent(machineID)
        if !id.isEmpty { return "machine:" + id }
        return "name:" + Self.normalizedMachineComponent(machineName)
    }

    private static func normalizedMachineComponent(_ raw: String) -> String {
        var value = raw.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        while value.hasSuffix(".") { value.removeLast() }
        return value
    }

    private static func identityKey(prefix: String, parts: [String]) -> String {
        prefix + "|" + parts.map { "\($0.utf8.count):\($0)" }.joined(separator: "|")
    }
}

private struct ArtifactPanelDisjointSet {
    private(set) var parent: [String: String] = [:]

    mutating func add(_ value: String) {
        if parent[value] == nil { parent[value] = value }
    }

    mutating func find(_ value: String) -> String {
        add(value)
        guard let direct = parent[value], direct != value else { return value }
        let root = find(direct)
        parent[value] = root
        return root
    }

    mutating func union(_ lhs: String, _ rhs: String) {
        let left = find(lhs)
        let right = find(rhs)
        guard left != right else { return }
        // Choosing the lexical root makes list IDs deterministic regardless of
        // manifest enumeration order.
        if left < right {
            parent[right] = left
        } else {
            parent[left] = right
        }
    }
}

struct ArtifactRecord: Codable, Identifiable, Hashable {
    let schemaVersion: Int
    let id: UUID
    var filename: String
    let createdAt: Date
    let kind: String
    let panel: ArtifactPanelContext
    let presentation: String
    let relativePath: String
    let byteCount: Int64
    /// Populated for explicit snapshots created from Files. Optional fields keep
    /// existing V1 render/screenshot manifests fully backwards compatible.
    let sourcePath: String?
    let contentType: String?

    init(
        id: UUID = UUID(),
        filename: String,
        createdAt: Date = Date(),
        kind: String = ArtifactKind.renderPDF,
        panel: ArtifactPanelContext,
        presentation: String,
        relativePath: String,
        byteCount: Int64,
        sourcePath: String? = nil,
        contentType: String? = nil
    ) {
        schemaVersion = 1
        self.id = id
        self.filename = filename
        self.createdAt = createdAt
        self.kind = kind
        self.panel = panel
        self.presentation = presentation
        self.relativePath = relativePath
        self.byteCount = byteCount
        self.sourcePath = sourcePath
        self.contentType = contentType
    }

    var isImage: Bool {
        kind == ArtifactKind.screenshotPNG
            || contentType?.lowercased().hasPrefix("image/") == true
            || ["png", "jpg", "jpeg", "gif", "bmp", "tiff", "tif", "webp", "heic", "heif", "ico", "icns"]
                .contains(fileExtension)
    }

    var isPDF: Bool { fileExtension == "pdf" || contentType?.lowercased() == "application/pdf" }
    var isMarkdown: Bool {
        let mediaType = contentType?
            .lowercased()
            .split(separator: ";", maxSplits: 1)
            .first?
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return mediaType == "text/markdown"
            || mediaType == "text/x-markdown"
            || ["md", "markdown", "mdown", "mkd"].contains(fileExtension)
    }
    var isFileSnapshot: Bool { kind == ArtifactKind.fileSnapshot }

    var fileExtension: String {
        let ext = (relativePath as NSString).pathExtension.lowercased()
        if !ext.isEmpty { return ext }
        if kind == ArtifactKind.screenshotPNG { return "png" }
        return kind == ArtifactKind.renderPDF ? "pdf" : ""
    }
}

enum ArtifactSortOrder: String, CaseIterable, Identifiable {
    case newest
    case oldest
    case nameAscending
    case nameDescending

    var id: String { rawValue }
    var title: String {
        switch self {
        case .newest: return "Newest first"
        case .oldest: return "Oldest first"
        case .nameAscending: return "Name A–Z"
        case .nameDescending: return "Name Z–A"
        }
    }
}

struct ArtifactPanelSummary: Identifiable, Hashable {
    let groupKey: String
    let context: ArtifactPanelContext
    let count: Int
    let lastSavedAt: Date
    var id: String { groupKey }
}

/// Pure library projections, kept out of SwiftUI so search/order behavior is
/// deterministic and straightforward to regression-test.
enum ArtifactLibraryQuery {
    static func records(
        _ records: [ArtifactRecord],
        panel: ArtifactPanelContext? = nil,
        filenameQuery: String = "",
        sort: ArtifactSortOrder = .newest
    ) -> [ArtifactRecord] {
        let needle = filenameQuery.trimmingCharacters(in: .whitespacesAndNewlines)
        let groups = panelGroups(records, including: panel.map { [$0] } ?? [])
        let selectedGroup = panel.map { groups[$0.semanticKey] ?? $0.semanticKey }
        let filtered = records.filter { record in
            (selectedGroup == nil || groups[record.panel.semanticKey] == selectedGroup)
                && (needle.isEmpty || record.filename.localizedCaseInsensitiveContains(needle))
        }
        return filtered.sorted { lhs, rhs in
            switch sort {
            case .newest:
                return lhs.createdAt == rhs.createdAt
                    ? lhs.id.uuidString < rhs.id.uuidString
                    : lhs.createdAt > rhs.createdAt
            case .oldest:
                return lhs.createdAt == rhs.createdAt
                    ? lhs.id.uuidString < rhs.id.uuidString
                    : lhs.createdAt < rhs.createdAt
            case .nameAscending:
                let comparison = lhs.filename.localizedCaseInsensitiveCompare(rhs.filename)
                return comparison == .orderedSame ? lhs.createdAt > rhs.createdAt : comparison == .orderedAscending
            case .nameDescending:
                let comparison = lhs.filename.localizedCaseInsensitiveCompare(rhs.filename)
                return comparison == .orderedSame ? lhs.createdAt > rhs.createdAt : comparison == .orderedDescending
            }
        }
    }

    static func panels(
        _ records: [ArtifactRecord],
        sort: ArtifactSortOrder = .newest
    ) -> [ArtifactPanelSummary] {
        let panelGroups = panelGroups(records)
        let groups: [ArtifactPanelSummary] = Dictionary(grouping: records, by: {
            panelGroups[$0.panel.semanticKey] ?? $0.panel.semanticKey
        })
            .values.compactMap { group -> ArtifactPanelSummary? in
                guard let latest = group.max(by: { $0.createdAt < $1.createdAt }) else { return nil }
                return ArtifactPanelSummary(
                    groupKey: panelGroups[latest.panel.semanticKey] ?? latest.panel.semanticKey,
                    context: latest.panel,
                    count: group.count,
                    lastSavedAt: latest.createdAt
                )
            }
        return groups.sorted { lhs, rhs in
            let nameComparison = lhs.context.sessionName.localizedCaseInsensitiveCompare(rhs.context.sessionName)
            switch sort {
            case .newest:
                return lhs.lastSavedAt == rhs.lastSavedAt
                    ? nameComparison == .orderedAscending
                    : lhs.lastSavedAt > rhs.lastSavedAt
            case .oldest:
                return lhs.lastSavedAt == rhs.lastSavedAt
                    ? nameComparison == .orderedAscending
                    : lhs.lastSavedAt < rhs.lastSavedAt
            case .nameAscending:
                return nameComparison == .orderedSame
                    ? lhs.lastSavedAt > rhs.lastSavedAt
                    : nameComparison == .orderedAscending
            case .nameDescending:
                return nameComparison == .orderedSame
                    ? lhs.lastSavedAt > rhs.lastSavedAt
                    : nameComparison == .orderedDescending
            }
        }
    }

    /// Build logical panel groups in two layers:
    /// 1. semantic identity rejoins a recreated session with the same name;
    /// 2. a non-reusable lineage joins aliases created by a rename or cwd move.
    /// Legacy manifests have no lineage and remain safely grouped by semantics.
    private static func panelGroups(
        _ records: [ArtifactRecord],
        including extraContexts: [ArtifactPanelContext] = []
    ) -> [String: String] {
        let contexts = records.map(\.panel) + extraContexts
        var set = ArtifactPanelDisjointSet()
        var firstSemanticForLineage: [String: String] = [:]
        for context in contexts {
            let semantic = context.semanticKey
            set.add(semantic)
            guard let lineage = context.lineageKey else { continue }
            if let first = firstSemanticForLineage[lineage] {
                set.union(first, semantic)
            } else {
                firstSemanticForLineage[lineage] = semantic
            }
        }
        var result: [String: String] = [:]
        for context in contexts {
            result[context.semanticKey] = set.find(context.semanticKey)
        }
        return result
    }
}

enum ArtifactFilename {
    static func generated(
        for panel: ArtifactPanelContext,
        at date: Date,
        fileExtension: String = "pdf"
    ) -> String {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.dateFormat = "yyyy-MM-dd HH.mm.ss"
        return normalized(
            panel.sessionName + " — " + formatter.string(from: date),
            fileExtension: fileExtension
        )
    }

    static func normalized(_ raw: String, fileExtension: String = "pdf") -> String {
        var name = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        for scalar in ["/", ":", "\n", "\r", "\t"] {
            name = name.replacingOccurrences(of: scalar, with: "-")
        }
        while name.contains("  ") { name = name.replacingOccurrences(of: "  ", with: " ") }
        if name.isEmpty { name = "Render" }
        let ext = safeExtension(fileExtension)
        let suppliedExtension = (name as NSString).pathExtension
        // Generated capture names end in a timestamp (`12.00.02`) before their
        // real extension is appended. Do not mistake the final seconds for an
        // extension; do replace actual extensions supplied during Rename.
        let suppliedLooksLikeType = suppliedExtension.unicodeScalars.contains {
            CharacterSet.letters.contains($0)
        }
        if !suppliedExtension.isEmpty,
           suppliedExtension.caseInsensitiveCompare(ext) == .orderedSame || suppliedLooksLikeType {
            name = (name as NSString).deletingPathExtension
        }
        if !ext.isEmpty { name += "." + ext }
        if name.count > 180 {
            let suffix = ext.isEmpty ? "" : "." + ext
            name = String(name.prefix(max(1, 180 - suffix.count)))
                .trimmingCharacters(in: .whitespaces) + suffix
        }
        return name
    }

    /// Preserve the source file's useful name and extension while removing path
    /// separators/control characters. Extension filtering also prevents a remote
    /// filename from escaping the immutable UUID blob path on disk.
    static func snapshot(_ sourceName: String) -> String {
        let ext = safeExtension((sourceName as NSString).pathExtension)
        return normalized(sourceName, fileExtension: ext)
    }

    static func safeExtension(_ raw: String) -> String {
        String(raw.lowercased().unicodeScalars.filter {
            CharacterSet.alphanumerics.contains($0)
        }.prefix(24))
    }
}

enum ArtifactDiskError: LocalizedError {
    case unsafePath

    var errorDescription: String? {
        switch self {
        case .unsafePath: return "The artifact record contains an unsafe file path."
        }
    }
}

struct ArtifactLoadIssue: Identifiable, Hashable {
    let manifest: String
    let reason: String
    var id: String { manifest }
}

struct ArtifactLoadReport {
    let records: [ArtifactRecord]
    let issues: [ArtifactLoadIssue]
}

/// Files are immutable UUID-named blobs with one small JSON manifest each.
/// This avoids a single ever-growing index becoming a corruption or contention
/// point, while keeping future artifact kinds possible without changing V1 UI.
actor ArtifactDiskStore {
    let rootURL: URL

    init(rootURL: URL) {
        self.rootURL = rootURL
    }

    func load() throws -> [ArtifactRecord] {
        try loadReport().records
    }

    /// Load every independent manifest without allowing one damaged record to
    /// hide the rest of the library. Unlike the original compactMap, every
    /// skipped file is reported to the UI instead of disappearing silently.
    func loadReport() throws -> ArtifactLoadReport {
        try prepareDirectories()
        let urls = try FileManager.default.contentsOfDirectory(
            at: recordsURL,
            includingPropertiesForKeys: nil,
            options: [.skipsHiddenFiles]
        ).filter { $0.pathExtension.lowercased() == "json" }
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        var records: [ArtifactRecord] = []
        var issues: [ArtifactLoadIssue] = []
        var seenIDs = Set<UUID>()
        for url in urls {
            let manifest = url.lastPathComponent
            let data: Data
            do {
                data = try Data(contentsOf: url)
            } catch {
                issues.append(ArtifactLoadIssue(manifest: manifest, reason: "Unreadable manifest: \(error.localizedDescription)"))
                continue
            }
            let record: ArtifactRecord
            do {
                record = try decoder.decode(ArtifactRecord.self, from: data)
            } catch {
                issues.append(ArtifactLoadIssue(manifest: manifest, reason: "Invalid manifest: \(error.localizedDescription)"))
                continue
            }
            guard record.schemaVersion == 1 else {
                issues.append(ArtifactLoadIssue(
                    manifest: manifest,
                    reason: "Unsupported schema version \(record.schemaVersion)"
                ))
                continue
            }
            let contentURL: URL
            do {
                contentURL = try self.contentURL(for: record)
            } catch {
                issues.append(ArtifactLoadIssue(manifest: manifest, reason: error.localizedDescription))
                continue
            }
            guard FileManager.default.fileExists(atPath: contentURL.path) else {
                issues.append(ArtifactLoadIssue(manifest: manifest, reason: "Saved content is missing at \(record.relativePath)"))
                continue
            }
            // Only a fully valid record claims its ID. If a damaged manifest
            // happens to sort before a healthy copy, the healthy artifact must
            // still load instead of being hidden as a supposed duplicate.
            guard seenIDs.insert(record.id).inserted else {
                issues.append(ArtifactLoadIssue(manifest: manifest, reason: "Duplicate artifact id \(record.id.uuidString)"))
                continue
            }
            records.append(record)
        }
        records.sort { $0.createdAt > $1.createdAt }
        return ArtifactLoadReport(records: records, issues: issues)
    }

    func savePDF(
        _ data: Data,
        panel: ArtifactPanelContext,
        presentation: String,
        createdAt: Date = Date(),
        id: UUID = UUID()
    ) throws -> ArtifactRecord {
        try prepareDirectories()
        let relativePath = "pdf/" + id.uuidString.lowercased() + ".pdf"
        // The manifest's ISO-8601 strategy persists whole seconds. Normalize
        // up front so the in-memory record and a record loaded after relaunch
        // are identical (the UI and generated filename are second-granular).
        let persistedCreatedAt = Date(timeIntervalSince1970: floor(createdAt.timeIntervalSince1970))
        let record = ArtifactRecord(
            id: id,
            filename: ArtifactFilename.generated(for: panel, at: persistedCreatedAt, fileExtension: "pdf"),
            createdAt: persistedCreatedAt,
            kind: ArtifactKind.renderPDF,
            panel: panel,
            presentation: presentation,
            relativePath: relativePath,
            byteCount: Int64(data.count)
        )
        let pdfURL = try contentURL(for: record)
        do {
            try data.write(to: pdfURL, options: .atomic)
            try writeManifest(record)
            return record
        } catch {
            try? FileManager.default.removeItem(at: pdfURL)
            throw error
        }
    }

    func saveScreenshotPNG(
        _ data: Data,
        panel: ArtifactPanelContext,
        createdAt: Date = Date(),
        id: UUID = UUID()
    ) throws -> ArtifactRecord {
        try prepareDirectories()
        let relativePath = "images/" + id.uuidString.lowercased() + ".png"
        let persistedCreatedAt = Date(timeIntervalSince1970: floor(createdAt.timeIntervalSince1970))
        let record = ArtifactRecord(
            id: id,
            filename: ArtifactFilename.generated(
                for: panel,
                at: persistedCreatedAt,
                fileExtension: "png"
            ),
            createdAt: persistedCreatedAt,
            kind: ArtifactKind.screenshotPNG,
            panel: panel,
            presentation: "clipboard-screenshot",
            relativePath: relativePath,
            byteCount: Int64(data.count)
        )
        let imageURL = try contentURL(for: record)
        do {
            try data.write(to: imageURL, options: .atomic)
            try writeManifest(record)
            return record
        } catch {
            try? FileManager.default.removeItem(at: imageURL)
            throw error
        }
    }

    func saveFile(
        _ data: Data,
        filename: String,
        panel: ArtifactPanelContext,
        sourcePath: String,
        contentType: String?,
        presentation: String,
        createdAt: Date = Date(),
        id: UUID = UUID()
    ) throws -> ArtifactRecord {
        try prepareDirectories()
        let record = fileRecord(
            filename: filename,
            byteCount: Int64(data.count),
            panel: panel,
            sourcePath: sourcePath,
            contentType: contentType,
            presentation: presentation,
            createdAt: createdAt,
            id: id
        )
        let destination = try contentURL(for: record)
        do {
            try data.write(to: destination, options: .atomic)
            try writeManifest(record)
            return record
        } catch {
            try? FileManager.default.removeItem(at: destination)
            throw error
        }
    }

    /// Streamed variant used for files that are not already visible in the Files
    /// editor. URLSession owns the temporary download; copy it into the immutable
    /// artifact store before that temporary file goes out of scope.
    func saveFile(
        at sourceURL: URL,
        filename: String,
        panel: ArtifactPanelContext,
        sourcePath: String,
        contentType: String?,
        presentation: String,
        createdAt: Date = Date(),
        id: UUID = UUID()
    ) throws -> ArtifactRecord {
        try prepareDirectories()
        let attributes = try FileManager.default.attributesOfItem(atPath: sourceURL.path)
        let byteCount = (attributes[.size] as? NSNumber)?.int64Value ?? 0
        let record = fileRecord(
            filename: filename,
            byteCount: byteCount,
            panel: panel,
            sourcePath: sourcePath,
            contentType: contentType,
            presentation: presentation,
            createdAt: createdAt,
            id: id
        )
        let destination = try contentURL(for: record)
        do {
            try FileManager.default.copyItem(at: sourceURL, to: destination)
            try writeManifest(record)
            return record
        } catch {
            try? FileManager.default.removeItem(at: destination)
            throw error
        }
    }

    func rename(_ record: ArtifactRecord, to requestedName: String) throws -> ArtifactRecord {
        var updated = record
        updated.filename = ArtifactFilename.normalized(
            requestedName,
            fileExtension: record.fileExtension
        )
        try writeManifest(updated)
        return updated
    }

    func delete(_ record: ArtifactRecord) throws {
        let manifest = manifestURL(for: record.id)
        let content = try contentURL(for: record)
        if FileManager.default.fileExists(atPath: manifest.path) {
            try FileManager.default.removeItem(at: manifest)
        }
        if FileManager.default.fileExists(atPath: content.path) {
            try FileManager.default.removeItem(at: content)
        }
    }

    private var recordsURL: URL { rootURL.appendingPathComponent("records", isDirectory: true) }
    private var pdfURL: URL { rootURL.appendingPathComponent("pdf", isDirectory: true) }
    private var imagesURL: URL { rootURL.appendingPathComponent("images", isDirectory: true) }
    private var filesURL: URL { rootURL.appendingPathComponent("files", isDirectory: true) }

    private func prepareDirectories() throws {
        try FileManager.default.createDirectory(at: recordsURL, withIntermediateDirectories: true)
        try FileManager.default.createDirectory(at: pdfURL, withIntermediateDirectories: true)
        try FileManager.default.createDirectory(at: imagesURL, withIntermediateDirectories: true)
        try FileManager.default.createDirectory(at: filesURL, withIntermediateDirectories: true)
    }

    private func fileRecord(
        filename: String,
        byteCount: Int64,
        panel: ArtifactPanelContext,
        sourcePath: String,
        contentType: String?,
        presentation: String,
        createdAt: Date,
        id: UUID
    ) -> ArtifactRecord {
        let persistedCreatedAt = Date(timeIntervalSince1970: floor(createdAt.timeIntervalSince1970))
        let ext = ArtifactFilename.safeExtension((filename as NSString).pathExtension)
        let suffix = ext.isEmpty ? "" : "." + ext
        return ArtifactRecord(
            id: id,
            filename: ArtifactFilename.snapshot(filename),
            createdAt: persistedCreatedAt,
            kind: ArtifactKind.fileSnapshot,
            panel: panel,
            presentation: presentation,
            relativePath: "files/" + id.uuidString.lowercased() + suffix,
            byteCount: byteCount,
            sourcePath: sourcePath,
            contentType: contentType
        )
    }

    private func manifestURL(for id: UUID) -> URL {
        recordsURL.appendingPathComponent(id.uuidString.lowercased() + ".json")
    }

    private func contentURL(for record: ArtifactRecord) throws -> URL {
        guard !record.relativePath.hasPrefix("/"), !record.relativePath.contains("..") else {
            throw ArtifactDiskError.unsafePath
        }
        let candidate = rootURL.appendingPathComponent(record.relativePath).standardizedFileURL
        let rootPath = rootURL.standardizedFileURL.path + "/"
        guard candidate.path.hasPrefix(rootPath) else { throw ArtifactDiskError.unsafePath }
        return candidate
    }

    private func writeManifest(_ record: ArtifactRecord) throws {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        try encoder.encode(record).write(to: manifestURL(for: record.id), options: .atomic)
    }
}

@MainActor
final class ArtifactStore: ObservableObject {
    nonisolated static var defaultRootURL: URL {
        FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Argus/artifacts", isDirectory: true)
    }

    @Published private(set) var records: [ArtifactRecord] = []
    @Published private(set) var loadIssues: [ArtifactLoadIssue] = []
    @Published private(set) var isLoading = true
    @Published var errorMessage: String?
    @Published var selectedPanelContext: ArtifactPanelContext?
    @Published var selectedArtifactID: UUID?
    @Published var query = ""
    @Published var sortOrder: ArtifactSortOrder = .newest

    let rootURL: URL
    private let disk: ArtifactDiskStore
    private let logEvents: Bool

    init(
        rootURL: URL = ArtifactStore.defaultRootURL,
        loadImmediately: Bool = true,
        logEvents: Bool = true
    ) {
        self.rootURL = rootURL
        disk = ArtifactDiskStore(rootURL: rootURL)
        self.logEvents = logEvents && !AppState.isRunningTests
        if loadImmediately {
            Task { await reload() }
        } else {
            isLoading = false
        }
    }

    var selectedArtifact: ArtifactRecord? {
        guard let selectedArtifactID else { return nil }
        return records.first { $0.id == selectedArtifactID }
    }

    func fileURL(for record: ArtifactRecord) -> URL {
        rootURL.appendingPathComponent(record.relativePath)
    }

    func count(for panel: ArtifactPanelContext) -> Int {
        ArtifactLibraryQuery.records(records, panel: panel).count
    }

    func openLibrary() {
        selectedArtifactID = nil
        selectedPanelContext = nil
        query = ""
    }

    func open(panel: ArtifactPanelContext) {
        selectedArtifactID = nil
        selectedPanelContext = panel
        query = ""
    }

    func open(artifact: ArtifactRecord) {
        selectedPanelContext = artifact.panel
        selectedArtifactID = artifact.id
        query = ""
    }

    func reload() async {
        isLoading = true
        do {
            let report = try await disk.loadReport()
            records = report.records
            loadIssues = report.issues
            if report.issues.isEmpty {
                errorMessage = nil
            } else {
                errorMessage = "\(report.issues.count) saved artifact\(report.issues.count == 1 ? "" : "s") could not be loaded. The remaining library is available and the affected files were left untouched."
            }
        } catch {
            errorMessage = error.localizedDescription
        }
        isLoading = false
    }

    func savePDF(
        _ data: Data,
        panel: ArtifactPanelContext,
        presentation: String
    ) async throws -> ArtifactRecord {
        let record = try await disk.savePDF(data, panel: panel, presentation: presentation)
        publish(record)
        return record
    }

    func saveScreenshotPNG(
        _ data: Data,
        panel: ArtifactPanelContext
    ) async throws -> ArtifactRecord {
        let record = try await disk.saveScreenshotPNG(data, panel: panel)
        publish(record)
        return record
    }

    func saveFile(
        _ data: Data,
        filename: String,
        panel: ArtifactPanelContext,
        sourcePath: String,
        contentType: String?,
        presentation: String
    ) async throws -> ArtifactRecord {
        let record = try await disk.saveFile(
            data,
            filename: filename,
            panel: panel,
            sourcePath: sourcePath,
            contentType: contentType,
            presentation: presentation
        )
        publish(record)
        return record
    }

    func saveFile(
        at sourceURL: URL,
        filename: String,
        panel: ArtifactPanelContext,
        sourcePath: String,
        contentType: String?,
        presentation: String
    ) async throws -> ArtifactRecord {
        let record = try await disk.saveFile(
            at: sourceURL,
            filename: filename,
            panel: panel,
            sourcePath: sourcePath,
            contentType: contentType,
            presentation: presentation
        )
        publish(record)
        return record
    }

    func rename(_ record: ArtifactRecord, to name: String) async throws -> ArtifactRecord {
        let updated = try await disk.rename(record, to: name)
        if let index = records.firstIndex(where: { $0.id == record.id }) {
            records[index] = updated
        }
        errorMessage = nil
        return updated
    }

    func delete(_ record: ArtifactRecord) async throws {
        try await disk.delete(record)
        records.removeAll { $0.id == record.id }
        if selectedArtifactID == record.id { selectedArtifactID = nil }
        errorMessage = nil
        guard logEvents else { return }
        ActivityJournal.shared.log("artifactDeleted", [
            "artifactID": record.id.uuidString.lowercased(),
            "filename": record.filename,
            "machineID": record.panel.machineID,
            "machine": record.panel.machineName,
            "session": record.panel.sessionName,
            "panelKey": record.panel.key,
        ])
    }

    private func publish(_ record: ArtifactRecord) {
        records.removeAll { $0.id == record.id }
        records.insert(record, at: 0)
        errorMessage = nil
        guard logEvents else { return }
        var fields: [String: Any] = [
            "artifactID": record.id.uuidString.lowercased(),
            "filename": record.filename,
            "kind": record.kind,
            "machineID": record.panel.machineID,
            "machine": record.panel.machineName,
            "session": record.panel.sessionName,
            "panelKey": record.panel.key,
            "presentation": record.presentation,
        ]
        if !record.panel.folder.isEmpty { fields["folder"] = record.panel.folder }
        if let lineage = record.panel.sessionLineageID, !lineage.isEmpty {
            fields["sessionLineageID"] = lineage
        }
        if let sourcePath = record.sourcePath { fields["sourcePath"] = sourcePath }
        if let contentType = record.contentType { fields["contentType"] = contentType }
        ActivityJournal.shared.log("artifactSaved", fields)
    }
}
